In [1]:
# import packages
import os
import sys
import numpy as np
import tensorflow as tf
tf.__version__

'1.12.0'

## tf.constant()

In [2]:
# constant is used to hold fixed numeric values
node1 = tf.constant(3.0, tf.float32) # nodes are nothing but tensors
node2 = tf.constant(4.5) # implicitly applied: float32

In [3]:
node1, node2

(<tf.Tensor 'Const:0' shape=() dtype=float32>,
 <tf.Tensor 'Const_1:0' shape=() dtype=float32>)

In [4]:
# create a session object to evaluate nodes
with tf.Session() as sess:
    sess.run(node1)

In [5]:
# you can evaluate multiple nodes at once
with tf.Session() as sess:
    print(sess.run([node1, node2]))

[3.0, 4.5]


In [6]:
node3 = tf.add(node1, node2) # add two nodes and assign to another node

In [7]:
node3

<tf.Tensor 'Add:0' shape=() dtype=float32>

In [8]:
# run the computation graph
with tf.Session() as sess:
    print(sess.run(node3))

7.5


## tf.placeholders()

In [9]:
# placeholders are used to hold variable input
a = tf.placeholder(tf.int32) # define the data type of the input
b = tf.placeholder(tf.int32)

In [10]:
adder_node = tf.add(a, b) # add two nodes

In [11]:
# evaluate computation graph
with tf.Session() as sess:
    print(sess.run(adder_node, feed_dict={a: 2, b: 4})) # use feed_dict to pass input to nodes

6


In [12]:
# evaluate computation graph
with tf.Session() as sess:
    print(sess.run(adder_node, feed_dict={a:[1, 2], b:[3, 10]})) # pass multiple input to nodes

[ 4 12]


In [13]:
with tf.Session() as sess:
    result = sess.run(adder_node, feed_dict={a:[2, 3, 4], b:[4, 5, 6]}) # save the result into another node
    print(result)

[ 6  8 10]


In [14]:
result, result.shape

(array([ 6,  8, 10], dtype=int32), (3,))

## tf.Variable()

In [15]:
# variable is used to hold values that keep changing during the process
# variable maintains state in the graph across calls to run
variable_a = tf.Variable(1.0, tf.float32)
variable_a

<tf.Variable 'Variable:0' shape=() dtype=float32_ref>

In [16]:
variable_b = tf.Variable([1.0, 2.0], tf.float32)
variable_b

<tf.Variable 'Variable_1:0' shape=(2,) dtype=float32_ref>

## Forward Pass Over Linear Regression with Unit Feature

In [17]:
weight = tf.Variable([1.0], tf.float32) # set intial weight as 1.0
bias = tf.Variable([1.0], tf.float32) # set initial weight as 1.0
x = tf.placeholder(tf.float32) # unit feature

model = weight * x + bias # vectorize linear model

# create placeholder for predicted value
y_original = tf.placeholder(tf.float32)

# create a error metric
error_measure = tf.squared_difference(model, y_original)

# create a loss function
loss_function = tf.reduce_mean(error_measure)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    # now run to evaluate the loss function
    print("Loss = ", sess.run(loss_function, feed_dict={x:[1, 2, 3, 4], y_original:[-1, -2, -3, -4]}))
    # predict
    print(sess.run(model, feed_dict={x:[1, 2, 3, 4], y_original:[-1, -2, -3, -4]}))

Loss =  41.0
[2. 3. 4. 5.]


## Iteration Using Another Weight and Bias Matrix

In [18]:
# now lets change weight and bais
weight = tf.Variable([-1.0], tf.float32) # set intial weight as 1.0
bias = tf.Variable([0.0], tf.float32) # set initial weight as 1.0
x = tf.placeholder(tf.float32) # unit feature

model = weight * x + bias # vectorize linear model

# create placeholder for predicted value
y_original = tf.placeholder(tf.float32)

# create a error metric
error_measure = tf.squared_difference(model, y_original)

# create a loss function
loss_function = tf.reduce_mean(error_measure)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    # now run to evaluate the loss function
    print("Loss = ", sess.run(loss_function, feed_dict={x:[1, 2, 3, 4], y_original:[-1, -2, -3, -4]}))
    # predict
    print(sess.run(model, feed_dict={x:[1, 2, 3, 4], y_original:[-1, -2, -3, -4]}))

Loss =  0.0
[-1. -2. -3. -4.]


## Sample Linear Regression With Unit Feature

In [19]:
a = list(range(100))
a[:3]

[0, 1, 2]

In [20]:
# get dummy data for now
# training data
x_train = np.array(range(0, 10)).reshape((10, 1))
y_train = x_train * 2

# validation data
x_val = np.array(range(80, 100)).reshape((20, 1))
y_val = x_val * 2

# test data
x_test = np.array([0, -1, 100]).reshape((3, 1))
y_test = np.array([0, -2, 200]).reshape((3, 1))

In [21]:
# first set some initial values for weight and bias: same as before
weight = tf.Variable([0.0], dtype=tf.float64)
bias = tf.Variable([0.0], dtype=tf.float64)

x = tf.placeholder(tf.float64) # placeholder
y = tf.placeholder(tf.float64)

linear_model = tf.add(tf.multiply(weight, x), bias) # model

loss_function = tf.reduce_mean(tf.square(tf.subtract(linear_model, y))) # minimize the loss function = mean squared difference

alpha = tf.constant(0.01) # set fixed learning rate

optimizer = tf.train.GradientDescentOptimizer(learning_rate=alpha) # use an optimizer to optimize the weights and bias

# use the optimizer to minimise the loss function
trainer = optimizer.minimize(loss_function)

In [22]:
# run the mode
with tf.Session() as sess:
    print("Training...")
    sess.run(tf.global_variables_initializer()) # initialize variables
    # run the optimizer for 1000 iterations
    for i in range(1000):
        sess.run(trainer, feed_dict={x:x_train, y:y_train})
        # print("Train Loss = ", sess.run(loss_function, feed_dict={x:x_train, y:y_train}))
        if i % 100 == 0:
            print("Validation Loss = ", sess.run(loss_function, feed_dict={x:x_val, y:y_val}))
            print("Weights = ", sess.run(weight))
            print("Bias = ", sess.run(bias))
            print()
    # now perform prediction
    print("Testing...")
    print("Test Loss = ", sess.run(loss_function, feed_dict={x:x_test, y:y_test}))
    print("Prediction = ", sess.run(linear_model, feed_dict={x:x_test})) # expected values are in y_test
    print("Original Values = ", y_test)

Training...
Validation Loss =  5921.296152321758
Weights =  [1.13999997]
Bias =  [0.18]

Validation Loss =  5.4553371056449595
Weights =  [1.97200412]
Bias =  [0.17555058]

Validation Loss =  1.7575809387018708
Weights =  [1.98410937]
Bias =  [0.09964354]

Validation Loss =  0.566251121840238
Weights =  [1.99098039]
Bias =  [0.05655826]

Validation Loss =  0.18243275511520562
Weights =  [1.99488041]
Bias =  [0.0321028]

Validation Loss =  0.058775530599852285
Weights =  [1.99709409]
Bias =  [0.01822174]

Validation Loss =  0.018936089602506995
Weights =  [1.99835059]
Bias =  [0.01034276]

Validation Loss =  0.006100761418479013
Weights =  [1.99906379]
Bias =  [0.00587061]

Validation Loss =  0.001965521428471433
Weights =  [1.9994686]
Bias =  [0.00333219]

Validation Loss =  0.0006332446428873661
Weights =  [1.99969837]
Bias =  [0.00189137]

Testing...
Test Loss =  8.772327361863822e-05
Prediction =  [[ 1.07965162e-03]
 [-1.99874817e+00]
 [ 1.99983862e+02]]
Original Values =  [[  0]
 [

As we can see that we didnt get the exact value but its very close and error has been reduced drastically.