In [2]:
# Import packages
import os
import sys
import numpy as np
import tensorflow as tf
tf.__version__

'1.12.0'

## Tensorflow APIs

### tf.constant()

It is used to hold fixed numeric values. Ex: 2, 3.4 etc.

In [3]:
node1 = tf.constant(3.0, tf.float32) # Nodes are nothing but tensors
node2 = tf.constant(4.5) # Implicitly applied: float32

In [4]:
node1, node2

(<tf.Tensor 'Const:0' shape=() dtype=float32>,
 <tf.Tensor 'Const_1:0' shape=() dtype=float32>)

In [7]:
# Always create a session object to evaluate nodes
with tf.Session() as sess:
    print(sess.run(node1))

3.0


In [8]:
# evaluate multiple nodes at once
with tf.Session() as sess:
    print(sess.run([node1, node2]))

[3.0, 4.5]


In [9]:
node3 = tf.add(node1, node2)
node3

<tf.Tensor 'Add:0' shape=() dtype=float32>

In [10]:
# Evaluate node
with tf.Session() as sess:
    print(sess.run(node3))

7.5


### tf.placeholders()

It is used to hold variables. It can change. Mostly used to assign weights, biases of a neural network.

In [11]:
a = tf.placeholder(dtype=tf.int32, shape=None, name="a") # Shape is not necessary
b = tf.placeholder(dtype=tf.int32, name="b") # Data type is must

In [12]:
adder_node = tf.add(a, b) # Operation on the placeholders

In [13]:
# Evaluate computation graph -> evaluate node
with tf.Session() as sess:
    print(sess.run(adder_node, feed_dict={a: 2, b: 4})) # Using feed_dict to pass input to the nodes for computation

6


In [14]:
# Evaluate computation graph
with tf.Session() as sess:
    print(sess.run(adder_node, feed_dict={a:[1, 2], b:[3, 10]})) # Can pass multiple input to nodes

[ 4 12]


In [15]:
# evaluate computation graph
with tf.Session() as sess:
    # Save results to access it outside the current session
    result = sess.run(adder_node, feed_dict={a:[2, 3, 4], b:[4, 5, 6]})
    print(result)

[ 6  8 10]


In [17]:
# Access outside the session object scope
result, result.shape

(array([ 6,  8, 10], dtype=int32), (3,))

### tf.Variable()

Variable is used to hold values that keep changing during the process like placeholder but variable maintains state in the graph across calls to run.

In [18]:
variable_a = tf.Variable(1.0, tf.float32) # assign variable
variable_a

<tf.Variable 'Variable:0' shape=() dtype=float32_ref>

In [19]:
variable_b = tf.Variable([1.0, 2.0], tf.float32)
variable_b

<tf.Variable 'Variable_1:0' shape=(2,) dtype=float32_ref>

## Forward pass of a linear regression model with unit feature

In [20]:
weight = tf.Variable([1.0], tf.float32) # Set intial weight as 1.0
bias = tf.Variable([1.0], tf.float32) # Set initial bais as 1.0

x = tf.placeholder(tf.float32) # Unit feature -> pass value using feed_dict

model = weight * x + bias # Linear regression model -> predicts

# Create placeholder for to hold original target value
y = tf.placeholder(tf.float32)

# Ereate a error metric
error_measure = tf.squared_difference(model, y)

# Loss function
loss_function = tf.reduce_mean(error_measure)

# Create a session to evaluate tensors
with tf.Session() as sess:
    # Do not forget to initialize global variables
    sess.run(tf.global_variables_initializer())
    # Now run multiple tensors
    print("Loss = ", sess.run(loss_function, feed_dict={x:[1, 2, 3, 4], y:[-1, -2, -3, -4]}))
    # Prediction
    print(sess.run(model, feed_dict={x:[1, 2, 3, 4], y:[-1, -2, -3, -4]}))

Loss =  41.0
[2. 3. 4. 5.]


## Using new weights and bias

In [21]:
weight = tf.Variable([-1.0], tf.float32) # Set intial weight as 1.0
bias = tf.Variable([0.0], tf.float32) # Set initial bais as 1.0

x = tf.placeholder(tf.float32) # Unit feature -> pass value using feed_dict

model = weight * x + bias # Linear regression model -> predicts

# Create placeholder for to hold original target value
y = tf.placeholder(tf.float32)

# Ereate a error metric
error_measure = tf.squared_difference(model, y)

# Loss function
loss_function = tf.reduce_mean(error_measure)

# Create a session to evaluate tensors
with tf.Session() as sess:
    # Do not forget to initialize global variables
    sess.run(tf.global_variables_initializer())
    # Now run multiple tensors
    print("Loss = ", sess.run(loss_function, feed_dict={x:[1, 2, 3, 4], y:[-1, -2, -3, -4]}))
    # Prediction
    print(sess.run(model, feed_dict={x:[1, 2, 3, 4], y:[-1, -2, -3, -4]}))

Loss =  0.0
[-1. -2. -3. -4.]
