In [1]:
# load packages
import os
import sys
import re
import numpy as np
import tensorflow as tf
from sklearn.datasets import load_boston
tf.__version__

'1.12.0'

In [2]:
# load data
boston = load_boston()
features = np.array(boston.data)
labels = np.array(boston.target)
features.shape, labels.shape

((506, 13), (506,))

In [3]:
labels = labels.reshape((len(labels), 1)) # reshape rank 1 array to have 1 dim
labels.shape

(506, 1)

In [4]:
features[0]

array([6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01, 6.575e+00,
       6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02,
       4.980e+00])

In [5]:
labels[0]

array([24.])

In [6]:
mean = np.mean(features, axis=0) # feature wise mean
std = np.std(features, axis=0) # feature wise standard deviation
# normalize feature now
features = (features - mean) / std
features.shape

(506, 13)

In [7]:
features[0]

array([-0.41978194,  0.28482986, -1.2879095 , -0.27259857, -0.14421743,
        0.41367189, -0.12001342,  0.1402136 , -0.98284286, -0.66660821,
       -1.45900038,  0.44105193, -1.0755623 ])

In [8]:
random_indices = np.random.rand(len(features)) < 0.80 # random indexes for splitting
# splti data
train_x = features[random_indices]
train_y = labels[random_indices]
val_x = features[~random_indices]
val_y = labels[~random_indices]

In [9]:
# set dimension
num_features = features.shape[1]
num_features

13

In [10]:
# create placeholders for input
x = tf.placeholder(dtype=tf.float32, shape=(None, num_features), name="feature_matrix") # num_samples x num_features
y = tf.placeholder(dtype=tf.float32, shape=(None, 1), name="target_vector") # num_sampels X 1

In [11]:
# define weight for the model
w = tf.Variable(tf.zeros(dtype=tf.float32, shape=(1, num_features)))

In [12]:
# define bais
b = tf.Variable(tf.zeros(dtype=tf.float32, shape=(1, num_features)))

In [13]:
# linear model
linear_model = tf.add(tf.multiply(w, x), b)

In [14]:
loss = tf.reduce_mean(tf.square(linear_model - y)) # define loss function

In [15]:
# set optimizer for weight updates
trainer = tf.train.AdamOptimizer(learning_rate=0.01).minimize(loss)

In [16]:
num_iterations = 10000

In [17]:
# run the mode
with tf.Session() as sess:
    print("[Training...]\n")
    sess.run(tf.global_variables_initializer()) # initialize variables
    # run the optimizer for 1000 iterations
    for i in range(num_iterations+1):
        sess.run(trainer, feed_dict={x:train_x, y:train_y})
        if i % 1000 == 0:
            print("Step", i, ":", end="\t")
            print("Train Loss: ", sess.run(loss, feed_dict={x:train_x, y:train_y}), end="\t")
            print("Validation Loss: ", sess.run(loss, feed_dict={x:val_x, y:val_y}))

[Training...]

Step 0 :	Train Loss:  569.3327	Validation Loss:  676.7248
Step 1000 :	Train Loss:  238.79741	Validation Loss:  301.08655
Step 2000 :	Train Loss:  106.13626	Validation Loss:  145.13638
Step 3000 :	Train Loss:  68.60378	Validation Loss:  93.228424
Step 4000 :	Train Loss:  63.693157	Validation Loss:  82.17353
Step 5000 :	Train Loss:  63.533283	Validation Loss:  80.76761
Step 6000 :	Train Loss:  63.53281	Validation Loss:  80.69479
Step 7000 :	Train Loss:  63.53278	Validation Loss:  80.69461
Step 8000 :	Train Loss:  63.53278	Validation Loss:  80.69448
Step 9000 :	Train Loss:  63.532784	Validation Loss:  80.694405
Step 10000 :	Train Loss:  63.53279	Validation Loss:  80.69436
